name: FluffyTales Merger
description: Merge all open Pull Requests of the Fluffytales Organisation
runs:
  using: node16
  main: dist/index.js
inputs:
  token:
    description: 'GitHub API token'
    required: true
outputs:
  changelogs:
    description: Changelog Message
