name: "merge them all"

on:
  workflow_dispatch

jobs:
  merge:
    runs-on: ubuntu-latest
    outputs:
      changelogs: ${{ steps.changelog.outputs.changelogs }}

    steps:
    - name: Fetch local action
      uses: actions/checkout@v3

    - name: Find Pull-Requests to deploy and prepare changelogs
      id: changelog
      uses: ./
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
  
  generate:
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
    - name: "add changelogs"
      run: |
        echo {\"message\":\""${{ needs.merge.outputs.changelogs }}"\"} > changelogs.json
    
    - uses: actions/upload-artifact@v2
      with:
        name: changelogs
        path: changelogs.json
    

