name: "merge them all"

on:
  workflow_dispatch

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch local action
      uses: actions/checkout@v3

    - name: Find Pull-Requests to deploy and prepare changelogs
      uses: ./
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
    
    - name: "add changelogs"
      run: |
        echo ${{ needs.prepare.outputs.changelogs }} > changelogs.json
    
    - uses: actions/upload-artifact@v2
      with:
        name: changelogs
        path: changelogs.json
    

